export const purple = '#A85ECC'
export const gray = '#D3D3D3'
export const white = '#FFFFFF'
export const red = '#B71845'
export const orange = '#F26F28'
export const blue = '#4E4CB8'
export const green = '#3CB371'
